
  banner:
    path: "banner.txt"

  smallrye-jwt:
    enabled: true
#CORS
app:
  cors:
    origins-allowed: "*"
  security:
    cors-allowed-origins: "*" # separado por vírgula



mp:
  jwt:
    verify:
      publickey:
        location: "publickey.pem"
      issuer: "http://localhost:8082/"
# for jwt expiration duration
com:
  quarkusjwt:
    jwt:
      duration: 3000 #300 = 5min
# for user's password simulation
    password:
      secret: mysecret
      iteration: 33
      keylength: 256


baseUrlFrontEnd: http://localhost:8081

code:
  quarkus:
    modules:
      multipart:
          MultipartService/mp-rest/url: http://localhost:8082/
      multipartsesp:
          MultipartServiceSesp/mp-rest/url: https://homolog2.sesp.mt.gov.br/ws-sesp-smtc/api/preocorrencia/upload